services:
  # Backend
  api:
    build: .
    container_name: spotify-api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model # Opcional: para montar modelos locales
    environment:
      - HF_TOKEN=${HF_TOKEN}

  # Frontend
  ui:
    build: .
    container_name: spotify-ui
    command: streamlit run ui/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000 
    depends_on:
      - api